name: "Quarto Extensions Updater"
description: "Automatically update Quarto extensions similar to Dependabot"
author: "Mickaël Canouil"

branding:
  icon: "package"
  color: "blue"

inputs:
  github-token:
    description: "GitHub token for creating pull requests"
    required: true
    default: ${{ github.token }}

  workspace-path:
    description: "Path to the workspace containing _extensions directory"
    required: false
    default: "."

  registry-url:
    description: "URL to the Quarto extensions registry JSON file"
    required: false
    default: "https://raw.githubusercontent.com/mcanouil/quarto-extensions/refs/heads/quarto-wizard/quarto-extensions.json"

  create-pr:
    description: "Whether to create a pull request for updates"
    required: false
    default: "true"

  branch-prefix:
    description: "Prefix for the update branch name"
    required: false
    default: "chore/quarto-extensions"

  base-branch:
    description: "Base branch to create pull requests against"
    required: false
    default: "main"

  pr-title-prefix:
    description: "Prefix for PR titles (e.g., 'chore(deps):' or 'build:')"
    required: false
    default: "chore(deps):"

  commit-message-prefix:
    description: "Prefix for commit messages (e.g., 'chore(deps):' or 'build:')"
    required: false
    default: "chore(deps):"

  pr-labels:
    description: "Comma-separated list of labels to add to PRs (e.g., 'dependencies,quarto-extensions,automated')"
    required: false
    default: "dependencies,quarto-extensions"

  auto-merge:
    description: "Enable automatic merging of PRs based on auto-merge-strategy"
    required: false
    default: "false"

  auto-merge-strategy:
    description: "Auto-merge strategy: 'patch' (patch only), 'minor' (minor and patch), 'all' (all updates)"
    required: false
    default: "patch"

  auto-merge-method:
    description: "Merge method to use: 'merge', 'squash', or 'rebase'"
    required: false
    default: "squash"

  include-extensions:
    description: "Comma-separated list of extensions to include (e.g., 'owner/name1,owner/name2'). If specified, only these extensions will be updated."
    required: false
    default: ""

  exclude-extensions:
    description: "Comma-separated list of extensions to exclude (e.g., 'owner/name1,owner/name2'). These extensions will be skipped."
    required: false
    default: ""

  group-updates:
    description: "Group all extension updates into a single PR instead of creating one PR per extension"
    required: false
    default: "false"

  update-strategy:
    description: "Control which types of updates to apply: 'all' (all updates), 'minor' (minor and patch only), 'patch' (patch only)"
    required: false
    default: "all"

  dry-run:
    description: "Run in dry-run mode: check for updates and report what would be done without creating PRs or making changes"
    required: false
    default: "false"

  create-issue:
    description: "In dry-run mode, create a GitHub issue with the update summary (defaults to false)"
    required: false
    default: "false"

  pr-reviewers:
    description: "Comma-separated list of GitHub usernames to request as reviewers on created PRs (e.g., 'user1,user2')"
    required: false
    default: ""

  pr-team-reviewers:
    description: "Comma-separated list of GitHub team slugs to request as reviewers on created PRs (e.g., 'team1,team2')"
    required: false
    default: ""

  pr-assignees:
    description: "Comma-separated list of GitHub usernames to assign to created PRs (e.g., 'user1,user2')"
    required: false
    default: ""

outputs:
  updates-available:
    description: "Whether updates are available (true/false)"

  update-count:
    description: "Number of updates available"

  updates:
    description: "JSON array of updates (name, currentVersion, latestVersion)"

  pr-number:
    description: "Pull request number (if created)"

  pr-url:
    description: "Pull request URL (if created)"

  issue-number:
    description: "Issue number (if created in dry-run mode)"

  issue-url:
    description: "Issue URL (if created in dry-run mode)"

runs:
  using: "node24"
  main: "dist/index.js"
