/**
 * Application-wide constants
 *
 * This module contains all hardcoded values used throughout the application.
 * Centralising constants improves maintainability and makes it easier to
 * update configuration values.
 */

// ============================================================================
// HTTP and Network Constants
// ============================================================================

/** HTTP 404 Not Found status code */
export const HTTP_NOT_FOUND = 404;

/** HTTP 422 Unprocessable Entity - Used by GitHub API to indicate a ref already exists */
export const HTTP_UNPROCESSABLE_ENTITY = 422;

/** Default HTTP request timeout in milliseconds */
export const DEFAULT_FETCH_TIMEOUT_MS = 30000; // 30 seconds

/** HTTP header for JSON content */
export const HTTP_HEADER_ACCEPT_JSON = "application/json";

/** User agent string for HTTP requests */
export const HTTP_USER_AGENT = "quarto-extensions-updater";

// ============================================================================
// Git and GitHub Constants
// ============================================================================

/** Git file mode for regular non-executable file */
export const GIT_FILE_MODE_REGULAR = "100644" as const;

/** Default base branch for pull requests */
export const DEFAULT_BASE_BRANCH = "main";

/** Default branch prefix for update branches */
export const DEFAULT_BRANCH_PREFIX = "chore/quarto-extensions";

/** Default prefix for PR titles */
export const DEFAULT_PR_TITLE_PREFIX = "chore(deps):";

/** Default prefix for commit messages */
export const DEFAULT_COMMIT_MESSAGE_PREFIX = "chore(deps):";

/** Default labels for pull requests */
export const DEFAULT_PR_LABELS = ["dependencies", "quarto-extensions"] as const;

/** Separator for label lists */
export const LABEL_SEPARATOR = ",";

// ============================================================================
// Quarto CLI Constants
// ============================================================================

/** Command to check Quarto CLI version */
export const QUARTO_VERSION_COMMAND = "quarto --version";

/** Command template for adding Quarto extensions (use with source parameter) */
export const QUARTO_ADD_COMMAND_TEMPLATE = "quarto add {source} --no-prompt";

/** Quarto extension manifest filenames */
export const QUARTO_MANIFEST_FILENAMES = ["_extension.yml", "_extension.yaml"] as const;

/** Quarto extensions directory name */
export const QUARTO_EXTENSIONS_DIR = "_extensions";

// ============================================================================
// Registry Constants
// ============================================================================

/** Default Quarto extensions registry URL */
export const DEFAULT_REGISTRY_URL =
	"https://raw.githubusercontent.com/mcanouil/quarto-extensions/refs/heads/quarto-wizard/quarto-extensions.json";

/** GitHub repository base URL */
export const GITHUB_BASE_URL = "https://github.com";

/** GitHub repository URL for this action */
export const ACTION_REPOSITORY_URL = "https://github.com/mcanouil/quarto-extensions-updater";

// ============================================================================
// PR and Documentation Constants
// ============================================================================

/** Footer text for auto-generated PRs */
export const PR_FOOTER_TEXT =
	`🤖 This PR was automatically generated by [quarto-extensions-updater](${ACTION_REPOSITORY_URL})` as const;

/** Instructions for setting up Quarto in GitHub Actions */
export const QUARTO_SETUP_INSTRUCTIONS = `In GitHub Actions, add this step before using quarto-extensions-updater:
  - name: Setup Quarto
    uses: quarto-dev/quarto-actions/setup@v2` as const;

// ============================================================================
// Validation Constants
// ============================================================================

/** Valid merge methods for GitHub PRs */
export const VALID_MERGE_METHODS = ["merge", "squash", "rebase"] as const;

/** Valid auto-merge strategies */
export const VALID_AUTO_MERGE_STRATEGIES = ["patch", "minor", "all"] as const;

/** Valid update strategies */
export const VALID_UPDATE_STRATEGIES = ["patch", "minor", "all"] as const;

/** URL protocol prefix for HTTPS */
export const HTTPS_PROTOCOL = "https://";

/** Invalid Git ref characters pattern */
export const INVALID_GIT_REF_CHARS = /[~^:?*[\]\\]/;

// ============================================================================
// Auto-Merge Constants
// ============================================================================

/** Delay in milliseconds before attempting to enable auto-merge (allows GitHub to compute mergeable state) */
export const AUTO_MERGE_INITIAL_DELAY_MS = 3000; // 3 seconds

/** Delay in milliseconds before retrying auto-merge after a "clean status" error */
export const AUTO_MERGE_RETRY_DELAY_MS = 3000; // 3 seconds

// ============================================================================
// Output and Logging Constants
// ============================================================================

/** Number of characters to use for separator lines in logs */
export const LOG_SEPARATOR_LENGTH = 60;

/** Character to use for separator lines */
export const LOG_SEPARATOR_CHAR = "─";
